sudo: false
language: scala
scala:
- 2.11.5
- 2.10.4
jdk:
- oraclejdk7
- oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
script:
- sbt ++$TRAVIS_SCALA_VERSION --warn update compile awsWrapTest/it:compile doc && sbt ++$TRAVIS_SCALA_VERSION awsWrapTest/it:test
