
name: "aws-wrap"

url: "http://dwhjames.github.io/aws-wrap"

baseurl: /aws-wrap

navigation:
- title: Getting started with DynamoDB
  url:   doc/dynamodb.html
- title: Getting started with S3
  url:   doc/s3.html

latestrelease: 0.8.0

markdown: kramdown
highlighter: pygments

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
